#  Template Java Spring Boot App for Elastic Beanstalk

#  This template allows you to deploy your application as code using AWS Elastic Beanstalk.
#  The workflow allows validate, linting and security scans on feature branches (as well as master).
#  The Spring Boot App will be validated and deployed after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/aws-elasticbeanstalk-deploy/src/master/README.md

image: atlassian/default-image:3

pipelines:
  default:
      - step:
          name: Build
          script:
            - chmod +x ./mvnw package --D
            - zip -j application.zip target/hello-world-0.0.1-SNAPSHOT.jar
          artifacts:
            - application.zip
      - step:
          name: Deploy to Dev
          deployment: Test
          trigger: automatic
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: 'books-backend-dev'
                ENVIRONMENT_NAME: 'Booksbackenddev-env'
                S3_BUCKET: 'books'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: 'books-backend-dev'
