
image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          trigger: automatic
          deployment: test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
              variables:
                AWS_ACCESS_KEY_ID: 'AKIAZNDUWQHL2MX3GWFL'
                AWS_SECRET_ACCESS_KEY: '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' 
                AWS_DEFAULT_REGION: 'us-east-1' 
                APPLICATION_NAME: 'books_backend'
                ENVIRONMENT_NAME: 'test'